run:
  tests: true

output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
  # deprecated linters
    - maligned
    - interfacer
    - scopelint
    - golint
    - nosnakecase
    - structcheck
    - exhaustivestruct
    - deadcode
    - varcheck
  # not wanted
    - depguard
    - gomnd
    - goerr113
    - ifshort
    - gochecknoglobals
    - varnamelen
    - wsl
    - lll
    - forbidigo
    - funlen
    - nestif
    #- gocognit
    #- goprintffuncname
    #- paralleltest
    #- nlreturn
    #- testpackage
    #- wrapcheck
    #- gci
    #- godot
    #- gofumpt
    #- cyclop
    #- errorlint
    #- tagliatelle
    #- thelper
    #- godox
    #- goconst

linters-settings:
  cyclop:
    max-complexity: 20
    package-average: 0.0
    skip-tests: false
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  gocyclo:
    min-complexity: 20
  govet:
    check-shadowing: true

issues:
  max-per-linter: 0
  max-same: 0
  exclude-use-default: false
  exclude:
    #- '^(G104|G204):'
    # Very commonly not checked.
    #- 'Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked'
    #- 'exported method (.*\.MarshalJSON|.*\.UnmarshalJSON) should have comment or be unexported'
    #- 'composite literal uses unkeyed fields'
    #- 'bad syntax for struct tag key'
    #- 'bad syntax for struct tag pair'
    #- 'result .* \(error\) is always nil'
